version: '3'
services:
  # my-app:
  #   image: 950387382710.dkr.ecr.ap-south-1.amazonaws.com/my-app:version1.4
  #   ports:
  #     - 3000:3000
  mongodb:
    image: mongo
    ports:
     - 27017:27017
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin                
     - MONGO_INITDB_ROOT_PASSWORD=kdjindal
    volumes:
     - mongo-data:/data/db
  mongo-express:
    image: mongo-express
    ports:
     - 8080:8081
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=admin                
     - ME_CONFIG_MONGODB_ADMINPASSWORD=kdjindal
     - ME_CONFIG_MONGODB_SERVER=mongodb
volumes:
  mongo-data:
    driver: local